import { gql } from '@apollo/react-hooks';

export const PHOTO_DETAILS = gql`
  fragment photoDetails on Photo {
    id
    width
    height
    color
    tiny
    small
    large
    downloadPage
    creditWeb
    creditId
    photographer
    description
    labels
    tags
    likes{
      edges{
        node{
          id
          user{
            id
          }
        }
      }
    }
    reviews{
      edges{
        node{
          id
          text
        }
      }
    }
    reviewCount
    collections{
      edges{
        node{
          id
          collection{
            id
          }
          photo{
            id
          }
        }
      }
    }
    likeCount
    collectionCount
    downloadCount
    reviewCount
    createdAt
  }
`;

export const COLLECTION_DETAILS = gql`
  fragment collectionDetails on Collection {
    id
    userId
    user {
      id
      username
    }
    photos{
      edges{
        node{
          id
          photo{
            id
            width
            height
            color
            tiny
            small
            large
            downloadPage
            creditWeb
            creditId
            photographer
            description
            labels
            tags
            likeCount
            collectionCount
            downloadCount
            reviewCount
            createdAt
          }
        }
      }
    }
    title
    description
    photoCount
    public
    cover
    reviews{
      edges{
        node{
          id
          text
        }
      }
    }
    reviewCount
    createdAt
    updatedAt
  }
`;

export const USER_DETAILS = gql`
  fragment userDetails on User {
    id
    username
    firstName
    lastName
    email
    profileImage
    likes{
      edges{
        node{
          id
          photo{
            ...photoDetails
          }
          createdAt
        }
      }
    }
    collections{
      edges{
        node{
          id
          user{
            id
            username
          }
          reviews{
            edges{
              node{
                id
                text
              }
            }
          }
          photos{
            edges{
              node{
                id
                photo{
                  ...photoDetails
                }
              }
            }
          }
          reviewCount
          title
          description
          photoCount
          createdAt
          public
          cover
        }
      }
    }
    likeCount
    collectionCount
  }
  ${PHOTO_DETAILS}
`;

export default PHOTO_DETAILS;
